// Generated by view binder compiler. Do not edit!
package bindings;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.ImageView;
import android.widget.RelativeLayout;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.w2sv.viewboundcontroller.test.R;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class ActivityTestBinding implements ViewBinding {
  @NonNull
  private final RelativeLayout rootView;

  @NonNull
  public final RelativeLayout dummy;

  @NonNull
  public final ImageView dummyIv;

  @NonNull
  public final TextView dummyTv;

  private ActivityTestBinding(@NonNull RelativeLayout rootView, @NonNull RelativeLayout dummy,
      @NonNull ImageView dummyIv, @NonNull TextView dummyTv) {
    this.rootView = rootView;
    this.dummy = dummy;
    this.dummyIv = dummyIv;
    this.dummyTv = dummyTv;
  }

  @Override
  @NonNull
  public RelativeLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static ActivityTestBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static ActivityTestBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.activity_test, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static ActivityTestBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      RelativeLayout dummy = (RelativeLayout) rootView;

      id = R.id.dummy_iv;
      ImageView dummyIv = ViewBindings.findChildViewById(rootView, id);
      if (dummyIv == null) {
        break missingId;
      }

      id = R.id.dummy_tv;
      TextView dummyTv = ViewBindings.findChildViewById(rootView, id);
      if (dummyTv == null) {
        break missingId;
      }

      return new ActivityTestBinding((RelativeLayout) rootView, dummy, dummyIv, dummyTv);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
